### ISSUE TITLE
Need return value in aceAttribClasses?

### ISSUE THREAD

**Issue by matthijskooijman** [mihai3/ep_code_formatting#1]
I installed this plugin with etherpad-lite 1.8.3, which produces the following error in my browser console:

> UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_code_formatting, function name: ep_code_formatting/static/js/index, hook: aceAttribClasses): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior.

Looks like aceAttribClasses needs a return value? Sounds like a trivial change, but I'm not quite familiar with the code...

**Comment by matthijskooijman** [comment]
The plugin does seem to work properly, so I guess this is indeed just a warning for future compatibility.

**Comment by mihai3** [comment]
Good catch, thanks! Fixed in 1.0.1.
